spring.application.name=carprice360

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=carprice360db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Abc@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080

jwt.secret=carprice360-super-secret-key-2024-very-long-string
jwt.expiration=86400000
upload.path=C:/Projects/frontend/image/cars/
# Cho phép upload file 
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB